---
# tasks file for roles/nginx

# waits until cloud-init is done downloading docker
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  become: true
  # retries until cloud-init is done downloading docker
  register: result  # Registering the output to a variable
  until: result is not failed  # Continue until the task does not fail
  retries: 50  # Retry up to 50 times
  delay: 5  # Wait for 5 seconds between retries

- name: Remove default Nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Upload custom Nginx configuration for CTFd
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/ctfd.conf
  notify:
    - reload nginx
  become: true

- name: Enable CTFd Nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/ctfd.conf
    dest: /etc/nginx/sites-enabled/ctfd.conf
    state: link
  notify:
    - reload nginx
  become: true

- name: Ensure Nginx is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
